meta_product_name: "Tanouki"
meta_title: "Tanouki"
meta_description: "Tanouki"
meta_image: "components/og-image-menu.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
